'use strict';
const $=id=>document.getElementById(id);
const defaults={target:200,salary:12,months:9,transition:35,'ai-cost':25};
let mode='payroll', latest=null;
const fmt=(n,d=0)=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d});
const modes={payroll:'首年人力成本 · 数学门槛',net:'首年净现金 · 数学门槛',annual:'稳定年化人力成本 · 数学门槛'};
function readInputs(){const p={};for(const id of Object.keys(defaults)){const el=$(id);if(el.value.trim()===''||!el.checkValidity())return null;p[id]=Number(el.value);}return p;}
function setPending(){latest=null;$('required-roles').textContent='—';$('gross-saving').textContent='待填';$('net-saving').textContent='待填';$('capacity-hours').textContent='待填';$('weekly-hours').textContent='待填';$('formula').textContent='请填写有效参数：年全成本大于 0，节约月数为 1—12，其他金额不得为负。';for(const key of ['gross','transition','ai','net']){$('bar-'+key).style.width='0%';$('bar-'+key+'-value').textContent='—';}$('sensitivity-body').replaceChildren();}
function calculate(){const p=readInputs();$('result-context').textContent=modes[mode];if(!p){setPending();return;}const factor=p.months/12;const required=mode==='annual'?Math.ceil(p.target/p.salary):Math.ceil((p.target+(mode==='net'?p.transition+p['ai-cost']:0))/(p.salary*factor));const annual=required*p.salary;const gross=annual*factor;const net=gross-p.transition-p['ai-cost'];const shownGross=mode==='annual'?annual:gross;latest={...p,mode,required,annual,gross,net};$('required-roles').textContent=fmt(required);$('gross-label').textContent=mode==='annual'?'完整年度人力成本减少':'首年人力成本减少';$('gross-saving').innerHTML=fmt(shownGross,shownGross%1?1:0)+'<span>万元</span>';$('net-label').textContent=mode==='annual'?'同一岗位情景的首年净额':'扣除过渡与 AI 后';$('net-saving').innerHTML=fmt(net,net%1?1:0)+'<span>万元</span>';$('roles-caption').textContent=mode==='annual'?'完整年度口径；首年按实际生效月份折算':'实际减少岗位或等值可避免支出的数学门槛';$('capacity-hours').innerHTML=fmt(required*1800)+'<span>小时</span>';$('weekly-hours').innerHTML=fmt(required*1800/(300*46),2)+'<span>小时 / 人 / 周</span>';$('chart-gross-label').textContent='首年人力';$('chart-net-label').textContent='首年净额';const scale=Math.max(gross,p.transition,p['ai-cost'],Math.abs(net),1);const values={gross,transition:p.transition,ai:p['ai-cost'],net};for(const [key,value] of Object.entries(values)){$('bar-'+key).style.width=(Math.abs(value)/scale*100)+'%';$('bar-'+key+'-value').textContent=(key==='transition'||key==='ai'?'−':'')+fmt(value,value%1?1:0);}$('formula').textContent=(mode==='annual'?`年化：${required} × ${p.salary} = ${fmt(annual,1)} 万元。首年：`:'')+`${required} × ${p.salary} × ${p.months}/12 = ${fmt(gross,1)} 万元；扣除 ${p.transition} 万过渡和 ${p['ai-cost']} 万 AI 费用，首年净额 ${fmt(net,1)} 万元。`;$('sensitivity-body').innerHTML=[10,12,14].map(c=>`<tr><th scope="row">${c} 万元 / 岗</th><td>${Math.ceil(p.target/c)} 岗</td><td>${Math.ceil(p.target/(c*factor))} 岗</td><td>${Math.ceil((p.target+p.transition+p['ai-cost'])/(c*factor))} 岗</td></tr>`).join('');}
for(const id of Object.keys(defaults))$(id).addEventListener('input',calculate);
function activateMode(button){mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>{const active=b===button;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('model-panel').setAttribute('aria-labelledby',button.id);calculate();}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>activateMode(b)));
$('reset-model').addEventListener('click',()=>{for(const [id,val] of Object.entries(defaults))$(id).value=val;activateMode($('mode-payroll'));toast('已恢复默认情景');});
function tabsKeyboard(selector,activate,vertical=false){const tabs=[...document.querySelectorAll(selector)];for(const tab of tabs)tab.addEventListener('keydown',e=>{let i=tabs.indexOf(tab);if(e.key===(vertical?'ArrowDown':'ArrowRight'))i=(i+1)%tabs.length;else if(e.key===(vertical?'ArrowUp':'ArrowLeft'))i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();tabs[i].focus();activate(tabs[i]);});}
tabsKeyboard('[data-mode]',activateMode);
const workflows={
 admissions:{owner:'招生负责人',title:'让咨询成为共享服务',description:'统一已核准的专业、收费和招生规则，AI 先形成有来源的答复草稿，顾问完成核实与发送。',steps:['咨询进入共享队列，识别需求与渠道','检索有效资料，生成答复和跟进建议','顾问核准发送，异常交主管处理'],kpi:'同渠道转化率、净处理分钟、收费信息准确率、投诉率。',cash:'高峰与日常排班均覆盖，验证后空缺不补；不计继续在岗人员的工资为节约。'},
 academic:{owner:'教务负责人',title:'把材料处理变成可追踪工单',description:'让识别、缺项提示和重复录入自动流转。资格、学籍与最终结果仍由授权人员核验。',steps:['统一上传入口与字段清单','识别材料并生成缺项、冲突工单','人工核原件与身份，登记最终结果'],kpi:'单件净处理时间、首次通过率、返工率、积压量与高峰等待。',cash:'集中处理后可合并排班，释放量足够形成完整岗位，并保留招生季弹性容量。'},
 admin:{owner:'财务 / 人事负责人',title:'把重复行政汇成共享后台',description:'对票据、制度咨询、对账和例行报表形成标准化初稿，资金审批与人事决定保留人工。',steps:['归集票据、报表和制度问题','规则校验与 AI 分类，生成可核对草稿','授权人员复核，记录异常与审批'],kpi:'对账差异、处理分钟、重复录入比例、人工复核量与结账时效。',cash:'同用人主体或合法共享安排下整合岗位；隐私权限、职责分离与必要复核不降低。'},
 credentials:{owner:'考评 / 国际教育负责人',title:'减少材料往返，守住授权决定',description:'AI 辅助翻译、资料比对、排程和缺项提示；认定结论、发证及重要申请决定由授权人员作出。',steps:['核对当期标准与合作院校要求','生成材料对照、翻译和排程草稿','授权人员复核，异常转专项处理'],kpi:'材料退回率、办理时长、复核差错、标准引用版本。',cash:'材料处理工时可合并为完整岗位；不以取消授权考评、资质或学生服务覆盖换取节约。'},
 contractors:{owner:'采购 / 财务负责人',title:'让外部用工也进入现金台账',description:'把季节性录入、文案与材料处理外包纳入统一流程，先核实已批准合同和预算，再评估减少空间。',steps:['收集合同、发票、预算与服务量','比较 AI 后真实剩余工作量','按合同调整续约或采购量，留存凭证'],kpi:'单位交付成本、实际采购量、交付质量、内部新增复核成本。',cash:'只计真实取消或减少的已批准支出，减去解约、替代与内部新增成本，避免与员工岗位重复。'}
};
function activateWorkflow(button){const w=workflows[button.dataset.workflow];document.querySelectorAll('[data-workflow]').forEach(b=>{const active=b===button;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('workflow-panel').setAttribute('aria-labelledby',button.id);$('workflow-tag').textContent=w.owner;$('workflow-title').textContent=w.title;$('workflow-description').textContent=w.description;$('workflow-steps').innerHTML=w.steps.map(s=>`<li>${s}</li>`).join('');$('workflow-kpi').textContent=w.kpi;$('workflow-cash').textContent=w.cash;}
document.querySelectorAll('[data-workflow]').forEach(b=>b.addEventListener('click',()=>activateWorkflow(b)));tabsKeyboard('[data-workflow]',activateWorkflow,true);
function csvDownload(rows,name){const csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+String(value).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已生成 CSV 下载文件');}
$('export-scenario').addEventListener('click',()=>{if(!latest){toast('请先补全有效参数');return;}const p=latest;csvDownload([['项目','值','口径'],['方案','广东江南理工教育集团 AI 人力优化','情景假设，不是已核实结果'],['目标模式',modes[mode],''],['目标万元',p.target,'用户目标'],['年全成本万元每岗',p.salary,'假设'],['首年平均节约月数',p.months,'假设'],['一次性过渡成本万元',p.transition,'假设'],['首年AI成本万元',p['ai-cost'],'假设'],['数学岗位门槛',p.required,'待岗位容量与用工路径核验'],['首年人力成本减少万元',p.gross,'测算'],['首年净现金万元',p.net,'测算'],['稳定年化工资减少万元',p.annual,'测算']], '江南理工_200万目标情景.csv');});
$('download-baseline').addEventListener('click',()=>csvDownload([['法定用人主体','校区','岗位分类','现有人数','年全成本每岗元','月任务量','原每件分钟','AI后含复核分钟','服务最低人数','增长预留人数','拟转岗人数','实际减少岗位','生效月份','一次性成本元','负责人'],['','','招生咨询','','','','','','','','','','','',''],['','','教务材料','','','','','','','','','','','',''],['','','财务人事','','','','','','','','','','','',''],['','','认定国际材料','','','','','','','','','','','',''],['','','外包临时用工','','','','','','','','','','','','']], '岗位基线采集模板.csv'));
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000);}
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('nav-links').classList.toggle('open',open);});document.querySelectorAll('#nav-links a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('nav-links').classList.remove('open');}));
calculate();activateWorkflow($('wf-admissions'));
